#!/bin/bash

# 🧪 Скрипт для настройки тестовых метрик Fodi Sushi в Go backend
# Этот скрипт должен быть выполнен на стороне Go backend

FODI_ID="55d9af69-c4d8-41f4-b587-35cd7ab75105"
GO_BACKEND="http://127.0.0.1:8080/api"

echo "🔍 Проверка текущего состояния Fodi Sushi..."
curl -s "$GO_BACKEND/businesses" | jq ".[] | select(.id==\"$FODI_ID\")"

echo ""
echo "📊 Проверка метрик (ожидается ошибка 'token not found')..."
curl -s "$GO_BACKEND/metrics/$FODI_ID"

echo ""
echo ""
echo "============================================"
echo "⚠️  ТРЕБУЕТСЯ ВРУЧНУЮ В GO BACKEND:"
echo "============================================"
echo ""
echo "Для полноценного тестирования CompareBusinesses нужно:"
echo ""
echo "1️⃣  Создать токен для Fodi Sushi:"
echo "   INSERT INTO tokens (id, business_id, symbol, initial_price, total_supply)"
echo "   VALUES (gen_random_uuid(), '$FODI_ID', 'FodiT', 15.75, 150);"
echo ""
echo "2️⃣  Создать тестовые транзакции (инвестиции):"
echo "   -- Получить token_id из предыдущего INSERT"
echo "   INSERT INTO transactions (id, token_id, user_id, type, quantity, price_per_token, total_amount)"
echo "   VALUES"
echo "     (gen_random_uuid(), '<token_id>', '<user_id>', 'BUY', 10, 15.75, 157.5),"
echo "     (gen_random_uuid(), '<token_id>', '<user_id>', 'BUY', 8, 16.20, 129.6),"
echo "     (gen_random_uuid(), '<token_id>', '<user_id>', 'BUY', 5, 17.00, 85.0);"
echo ""
echo "3️⃣  Проверить метрики:"
echo "   curl http://127.0.0.1:8080/api/metrics/$FODI_ID | jq '.'"
echo ""
echo "============================================"
echo ""
echo "После этого выполните тест сравнения:"
echo "curl -X POST http://127.0.0.1:8000/api/v1/chat \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"user_id\":\"test\",\"message\":\"сравни Tech Startup и Fodi Sushi\"}' | jq '.'"
echo ""
